### ISSUE TITLE
pantry dependencies casa-client and casa-types have not been released to hackage

### ISSUE THREAD

**Issue by cdepillabout** [commercialhaskell/pantry#16]
It looks like [`pantry-0.3.0.0`](https://hackage.haskell.org/package/pantry-0.3.0.0) has been released to Hackage.

However, it looks like `casa-client` and `casa-types` have not been released, so it is not possible to actually build `pantry` from Hackage.

I thought that possibly it was just an oversight not releasing `casa-client` and `casa-types`.

**Comment by chrisdone** [comment]
Uploaded!

http://hackage.haskell.org/package/casa-client
http://hackage.haskell.org/package/casa-types

**Comment by cdepillabout** [comment]
Thanks!
