### ISSUE TITLE
Hard-coded URLs for snapshots prevents mirroring

### ISSUE THREAD

**Issue by dramforever** [commercialhaskell/pantry#19]
https://github.com/commercialhaskell/pantry/blob/05d9896da3b7545c49bdefb38b16437caa13b71e/src/Pantry/Types.hs#L1906-L1933

This prevents mirroring of these snapshots to mitigate slow downloading speed in certain areas. In particular, the mirror hosted by TUNA is no longer working because new snapshots are only available through pantry and the problem is tracked at https://github.com/tuna/tunasync-scripts/issues/50.

**Comment by snoyberg** [comment]
Do you want to send a PR for your desired change?

**Comment by dramforever** [comment]
Well, I'm honestly not sure what to do here, so I posted this hoping to receive some comments on this matter. I guess I didn't make that intention clear.

The reason I'm here dipping a bit into this problem is that TUNA is a student association, and the person who originally set up stackage mirroring is no longer at the university. So since the stackage mirror broke, and apparently I know some Haskell, I was the one asked to take a look.

I'm not really familiar with how stack or pantry works, but if I do end up learning more about them and figuring out a way a pantry mirror could work, I'd be happy to discuss or make a PR.

**Comment by acondolu** [comment]
Hello everybody. Any news on this? I am interested in solving this issue, and I volunteer to start working on a PR. I will propose a solution in a PR draft by next week, so that we can discuss and find the best solution.
