### ISSUE TITLE
Tar type detected incorrectly on Windows

### ISSUE THREAD

**Issue by rossng** [commercialhaskell/pantry#23]
I came across a couple of Pantry issues while attempting to build [concur-replica](https://github.com/pkamenarsky/concur-replica) on Windows with the latest Stack (2.3.1).

When I run `stack build`, I get the following error message

```
Cloning 46d2fd3b2c236d573f1d6002eb58cc95b2ba03b9 from https://github.com/pkamenarsky/replica.git
←[0mCloning dc5347b35c79654d58fa95716f425ee7248504fb from https://github.com/pkamenarsky/concur.git←[0m
←[0mReceived ExitFailure 128 when running
Raw command: "C:\\Program Files\\Git\\cmd\\git.EXE" submodule foreach --recursive "git -c core.autocrlf=false archive --prefix=$displaypath/ -o bar.tar HEAD; rm -rf temp; mkdir temp; mv bar.tar temp/; tar  -C temp -xf temp/bar.tar; rm temp/bar.tar; tar  -C temp -rf C:\\Users\\Ross Gardiner\\AppData\\Local\\Temp\\with-repo-archive17680\\foo.tar . ;"
Run from: C:\Users\Ross Gardiner\AppData\Local\Temp\with-repo17681\cloned
Standard output:

Entering 'concur-vdom/ghcjs-ffiqq'
Standard error:

tar: Cannot connect to C: resolve failed
fatal: run_command returned non-zero status for concur-vdom/ghcjs-ffiqq
.
←[0m
```

I did a bit of digging and it seems like this comes from a call to `archiveSubmodules`. Pantry detects (using `getTarType`) that my Windows 10 installation has BSD `tar` installed. Indeed it does - it now comes with Windows by default.

```
> tar --version
bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.5.f-ipp
```

However, the problem arises because `tar` is actually being called *inside* `git submodule foreach`. Instead of executing these commands in a Windows-like shell, Git executes them inside a Bash-like shell with (it seems) access to all the MSYS2 utilities. So, in fact, when `tar` is called, it starts GNU Tar - not the BSD tar installed on my system.

GNU Tar does not handle Windows paths as well as BSD Tar. It interprets colons in file paths as signifying a remote file system, which of course causes problems for any absolute Windows path (e.g. `C:\foo\bar`). There is a `--force-local` flag in GNU Tar which forces it to handle colons correctly by interpreting paths as local. This issue has actually [already been fixed](https://github.com/commercialhaskell/stack/issues/4865) in Pantry when it used to be part of Stack. 

The new problem here is that Pantry *detects* BSD Tar but then it's GNU Tar that actually runs. So the `--force-local` option is never passed and GNU Tar tries to interpret the path as a remote path.

---

The second issue I came across is that the `tarball` path is not quoted. On Windows, it's quite likely that this path will have spaces in.

**Comment by rossng** [comment]
Looks like this is connected to https://github.com/commercialhaskell/stack/issues/5135 and #9.

**Comment by snoyberg** [comment]
Do you have a recommendation of how to fix this?

**Comment by rossng** [comment]
As far as I can see, there are three approaches.

## 1) Change `getTarType` to figure out which `tar` Git will launch

The first option is to update `getTarType` to figure out which kind of `tar` executable will be executed inside the `git submodule foreach` sub-shell.

I guess you could execute something like `git submodule foreach 'tar --version'` and inspect the output in much the same way as it works currently.

One downside of this is that `tar --version` may be executed between 0 and n times depending on how many submodules there are. I looked to see if there was a way to execute a command exactly once in a Git sub-shell. That doesn't seem to exist. 

(If you want to investigate further, [`git submodule`](https://github.com/git/git/blob/master/builtin/submodule--helper.c) calls a function [`run_command`](https://github.com/git/git/blob/master/run-command.h) to launch the sub-shell. I couldn't see anywhere in the Git codebase where this functionality is exposed directly to the user.)

## 2) Figure out which type of `tar` Git is using *inside* the sub-shell

The next option is to instead determine the type of `tar` *inside* the command that is executed in the sub-shell. All the logic would be inside the strings passed to `runGitCommand`.

The downside of this is that you will end up with a rather complicated Bash script executing inside `git submodule foreach`. This might not work consistently across platforms and will be hard to read.

## 3) Don't execute `tar` in the sub-shell

Another option is to simply use `git submodule foreach` to print out the paths of each submodule. For example:

```
$ git submodule foreach --recursive 'echo $sm_path'
Entering 'ghcjs-ffiqq'
concur-vdom/ghcjs-ffiqq
Entering 'ghcjs-vdom'
concur-vdom/ghcjs-vdom
```

You could then parse this output and then call `rm`/`mkdir`/`mv`/`tar` with the appropriate paths directly from Haskell (*outside* of the `git submodule foreach` context).

I think this is my favourite option.

**Comment by snoyberg** [comment]
I like (3) as well. And your clear breakdown here definitely helped me understand what's going on.

Any chance you'd like to take a stab and making a PR to fix this?

**Comment by rossng** [comment]
I'm happy to have a go at it. My only concern is that, when executing `tar` in the normal shell, we are likely to come across systems that do not have it (e.g. Windows 10 pre-2017; Windows 7). 

Do you have any ideas for solving this?

**Comment by rossng** [comment]
I've just noticed that Stack already makes use of Haskell's own [tar](https://hackage.haskell.org/package/tar) library. Perhaps that's the best route to go.

**Comment by snoyberg** [comment]
We've been moving over to `tar-conduit` in Stack recently. I'm not sure if there was a reason to stick with shelling out to the `tar` executable instead. @psibi do you remember any reason to do that?

**Comment by psibi** [comment]
Unfortunately I don't remember why we were calling out to `tar`. IIRC, the shelling out to tar code was present before I started working on it.

**Comment by snoyberg** [comment]
Got it. I'm not sure either. @rossng if you want to take a crack at porting this over to `tar-conduit`, I'd say go for it. Just be advised that there may be some reason we avoided doing this in the past that no one can remember.

**Comment by rossng** [comment]
Having looked at `tar-conduit`, it seems that there is currently no way to append to a tar file. It is possible, of course, to do `untarChunks` and then stick a bunch of new `TarChunk`s on the end of the stream, but this seems wasteful from a performance perspective. 

Ideally, we should just be able to rip the two terminating blocks (of all zeros) off the end, append the new content and then add a new terminator. There are probably some additional issues to consider like clashing filenames.

Do you have a preferred design for how `tar-conduit` should be changed?

**Comment by snoyberg** [comment]
Why do we need the ability to append to existing tar files?

**Comment by rossng** [comment]
That's what [`archiveSubmodules`](https://github.com/commercialhaskell/pantry/blob/0af8b78f37e1d328874856e86de93ac5ae485b40/src/Pantry/Repo.hs#L146) does. It is called as part of [`createRepoArchive`](https://github.com/commercialhaskell/pantry/blob/0af8b78f37e1d328874856e86de93ac5ae485b40/src/Pantry/Repo.hs#L186), which creates a tarball of an entire git repository (though I haven't looked into exactly *why* this is necessary).

`createRepoArchive` first calls [`git archive`](https://git-scm.com/docs/git-archive) to tar the main repository. For some reason, `git archive` ignores submodules, so `archiveSubmodules` is used to append each submodule to the existing tarball.

I suppose another option would be to completely forgo `git archive` and just recursively tar the entire folder in one go (excluding `.git/`). There is a risk that maybe `git archive` does something special, but I'm not sure what it would be.

**Comment by snoyberg** [comment]
I don't have any strong opinions on these topics.

**Comment by dpwiz** [comment]
Still broken on 2.5.1 with basically the same error.

**Comment by rossng** [comment]
I never managed to tackle this - turns out the world of `tar` files is crazily complicated. So many half-documented standards! I didn't have time to gain enough knowledge to be confident that I wouldn't be creating totally invalid files.
