### ISSUE TITLE
OpenBSD tar is not detected

### ISSUE THREAD

**Issue by blackgnezdo** [commercialhaskell/pantry#33]
When running `stack` I get this error:
```
2021-05-09 21:20:54.625664: [debug] Run process within /tmp/with-repo54077/cloned: /bin/tar --version
2021-05-09 21:20:54.975595: [error] Received ExitFailure 1 when running
Raw command: /bin/tar --version
Run from: /tmp/with-repo54077/cloned
Standard error:

tar: unknown option -- -
usage: tar {crtux}[014578befHhjLmNOoPpqsvwXZz]
           [blocking-factor | archive | replstr] [-C directory] [-I file]
           [file ...]
       tar {-crtux} [-014578eHhjLmNOoPpqvwXZz] [-b blocking-factor]
           [-C directory] [-f archive] [-I file] [-s replstr] [file ...]
```

I suspect this is due to `pantry` trying to [work out the tar version](https://github.com/commercialhaskell/pantry/blob/c7923fc963e36efd179ba301ac426139a9dc182d/src/Pantry/Repo.hs#L32). I doubt `--version` is in any relevant standard that OpenBSD follows, so `tar` exits with error code 1 in such cases.

**Comment by snoyberg** [comment]
I'm not familiar with OpenBSD tar, but I'm guessing the BSD variant here would be the sensible default. Can you confirm?

@psibi any thoughts on modifying this code to always choose BSD in the case of failing to parse the `--version` string, for any reason?

**Comment by psibi** [comment]
> any thoughts on modifying this code to always choose BSD in the case of failing to parse the --version string, for any reason?

Yeah, that sounds good to me.
