### ISSUE TITLE
Incompatible with aeson-2.0

### ISSUE THREAD

**Issue by goldfirere** [commercialhaskell/pantry#46]
I naively tried saying `cabal install stack` today, to find that pantry failed to compile, as `cabal` chose to use `aeson-2.0.3.0`. That doesn't work -- there are type errors in `AesonExtended`. Switching to `aeson-1.5.6.0` works better. Is it possible to add a version bound to recent releases of pantry?

**Comment by snoyberg** [comment]
If someone wants to add revisions on Hackage, I'll grant them access to do so, but I don't spend my time on that.

**Comment by snoyberg** [comment]
Also, we strongly advise _against_ using Stack executable built like that, as we can't verify which dependency versions cabal chooses. We've run into many spurious bug reports based on this in the past.

**Comment by goldfirere** [comment]
I suppose I could add the bound on Hackage. You're right that the final stack executable didn't work (wouldn't install GHC on macOS/aarch64), but at least it built.

**Comment by NickGeek** [comment]
I also get the error:
```
Last 15 lines from /Users/nick/Library/Logs/Homebrew/haskell-stack/02.cabal:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap Value’
                     with ‘HashMap Text v0’
      Expected type: HashMap Text v0
        Actual type: Object
    • In the first argument of ‘HashMap.keys’, namely ‘obj’
      In the first argument of ‘Set.fromList’, namely
        ‘(HashMap.keys obj)’
      In the first argument of ‘Set.difference’, namely
        ‘(Set.fromList (HashMap.keys obj))’
    |
124 |                              (Set.fromList (HashMap.keys obj))
    |                                                          ^^^
cabal: Failed to build pantry-0.5.3 (which is required by stack-2.7.4). See
the build log above for details.
```

When trying to build this package as part of building `stack`.

**Comment by mpilgrem** [comment]
I am closing this issue because `pantry-0.5.4` on Hackage and Stackage supports `aeson >= 2`.

**Comment by Bodigrim** [comment]
As a Hackage trustee, I made revisions to prohibit unbuildable configurations:
https://hackage.haskell.org/package/pantry-0.4.0.0/revisions/
https://hackage.haskell.org/package/pantry-0.4.0.1/revisions/
